### ISSUE TITLE
Use grave as a hotkey

### ISSUE THREAD

**Issue by Scridgeon** [Blackstareye/toggleAudio-blackeyeprojects.de#10]
I have a customer script that I use to toggle the audio output device. I want to replace my script with your extension.
I currently use ( <Super> + ` ) as the hotkey combination but I am unable to get the grave key to work.

I've tried ['<Super>grave'] and ['<Super>`'] but neither of them toggle the audio change.
I did confirm that the default hotkey combination does toggle the audio source.

How do I get my key combination to work? Or how can I invoke the toggle if I want to add it to a script?

![image](https://github.com/user-attachments/assets/3b3b818f-7c96-422f-bdc5-1b194c22a2e4)

**Comment by Blackstareye** [comment]
Hey :) first of all thx for using my extension! :) 

I will look into that and answer then. I had to try this out in my vm :) 


>How do I get my key combination to work? Or how can I invoke the toggle if I want to add it to a script?
I think that is not possible so far, regarding how gnome extensions work, but I might be wrong there

**Comment by Blackstareye** [comment]
Okay it's a bit more complicated but not much.



if you have a standard US layout it depends on:

* whether you have a layout **with deadkeys** 
   *  --> then you need `dead_grave`
* or have a layout **without deadkeys** 
   *   --> then you need `grave` 

You can check, what key works for you, if you go to the hotkey settings of your distribution, and try your combination on a command there. You see the displayed combination and how the key is called.

<hr>
Moreover: 
Check if another program, action or (maybe your script?) uses and occupies the keys.
Then my extension can't receive them.

I tried your combination with

"['<Ctrl><Super>dead_grave']" 
and
"['<Ctrl><Super>grave']" 

and both worked for me, depending on which layout I use.

Hope that helps :)

**Comment by Scridgeon** [comment]
Thanks for getting back to me so quickly. I reviewed your gsettings string this was user error. I was passing "['<Super>grave']" to select-headphone-key instead of toggle-headphone-key. I used your command and everything is working great. I'll absolutely add a review; thanks again for the help.

**Comment by Blackstareye** [comment]
Glad it could be solved :D  

You are welcome :> :)
