### ISSUE TITLE
Gnome 47 compatibility

### ISSUE THREAD

**Issue by Switch123456789** [Blackstareye/toggleAudio-blackeyeprojects.de#12]
I would love to continue using this extension on the latest gnome desktop!

**Comment by Blackstareye** [comment]
Hey :) I will check if there are any problems with "just bumping up the version" :) 

Glad to hear that you like my extension so far :> :D

**Comment by Switch123456789** [comment]
I bumped the version myself yesterday for a test-drive and used it a few times, I noticed no issue so far :)

Yea, it's a simple but very useful extension. :)

**Comment by Blackstareye** [comment]
Sounds great - I will test the version tomorrow and bump the version :) 

I will let you know when the review is done and the new version is there :) 

<hr>
hence you like the extension - little self advertisement here :) 
I would appreciate it if you let a review here [review](https://extensions.gnome.org/extension/7080/toggle-headphone/)  

This helps the extension to grow so others can see and use this extension as well :)  
This also helps to get maybe someday a donation which supports projects like that and helps me doing freelancing stuff :)

**Comment by Blackstareye** [comment]
hey @Switch123456789 , version is approved :) 

I tested it as well. It should be working as aspected :) 
#Gnome47Support

**Comment by Switch123456789** [comment]
@Blackstareye Hey thank you :) If I ever create an account on the gnome extensions page, I will make sure to vote for your extension! However, I gave it a star here on github and tipped 2€ on ko-fi! :3

**Comment by Blackstareye** [comment]
Aww
Thank you, really appreciate it :> ^.^
