### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by hrandib** [Blackstareye/toggleAudio-blackeyeprojects.de#3]
It would be useful to have an option to set hotkeys for
- Toggle switch
- Headphone selection
- Speaker selection

**Comment by Blackstareye** [comment]
I will look into that and if it is suitable there. Global Hotkeys are kinda fuzzy sometimes.

**Comment by Blackstareye** [comment]
Review is pending  :) You can test it @hrandib  if you want (using the branch `feature_hotkeys`. Or you wait until the review is passed :) 

Meanwhile:
 I would appreciate it if you let a review here if you got time for that [review](https://extensions.gnome.org/extension/7080/toggle-headphone/)  :)

**Comment by hrandib** [comment]
Works fine for me except one thing, can't set a custom hotkey via dconf-editor. Maybe more instructions will help. The extension is installed by replacing content in the .local/gnome-shell with PR. 
![Screenshot from 2024-07-10 19-38-04](https://github.com/Blackstareye/toggleAudio-blackeyeprojects.de/assets/17005110/3c7f47d7-6df0-43e3-a7df-a644fd4a571c)

**Comment by Blackstareye** [comment]
Ahh I see. They are not visible until they are changed. 
I will look into that.

But this needs a bit of time. I have to check that :D

PS: thx for the review ^.^

**Comment by Blackstareye** [comment]
@hrandib  Okay. I will add it to the readme but please find an instruction here:
https://github.com/Blackstareye/toggleAudio-blackeyeprojects.de/wiki/Changing-hotkeys:

Hope that helps :)

**Comment by Blackstareye** [comment]
I will wait until your confirm you understand my instructions :) . Then I will close this issue :)

**Comment by Blackstareye** [comment]
@jtaus from the matrix channel mentioned that this is a bug in `dconf-editor` (https://github.com/paperwm/PaperWM/issues/887)
So you can use dconf editor as well :) I put the necessary codeline in the wiki entry :)

**Comment by hrandib** [comment]
The first approach works fine for me but not the second, no luck with dconf-editor:
GSETTINGS_SCHEMA_DIR=::$HOME/.local/share/gnome-shell/extensions/toggleAudio@blackeyeprojects.de/schemas dconf-editor

** (dconf-editor:387468): CRITICAL **: 08:47:02.851: source_manager_try_prepend_dir: assertion 'schemas_dir != NULL' failed
Segmentation fault (core dumped)

**Comment by hrandib** [comment]
I'm on Ubuntu 24.04

**Comment by Blackstareye** [comment]
Weird. But I can't help you there.
I link you to the matrix channel and the issue :) 

Issue: https://github.com/paperwm/PaperWM/issues/887

Matrix Channel: https://matrix.to/#/!hCGqHbXRuMrvWnudnP:gnome.org/$cA5eRVwJmeQVm3okUVenlALcSGdTUchdi__xyIYuz5w?via=gnome.org&via=matrix.org&via=envs.net

Linked Bug: https://gitlab.gnome.org/GNOME/dconf-editor/-/blob/master/editor/source-manager.vala#L127 

Hope they can help you there :) 

Matrix Link for gnome extension is this one: https://matrix.to/#/#extensions:gnome.org 

I am glad that it worked with the first approach though :> Enjoy your hotkeys ! :D   

I will close this one, soon then :)

**Comment by hrandib** [comment]
The result is achieved, the only issue is the hotkey setting is a bit inconvenient. Anyway thank a lot for the support
